version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  build_and_run:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run
          command: npm run dev
workflows:
  heroku_deploy:
    jobs:
      - build_and_run
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          app-name: $HEROKU_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: master