version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-and-run:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "12.22"
      - node/install-packages
      - run:
        command: npm install
      - run:
          command: npm run dev
workflows:
  build-and-run:
    jobs:
      - build-and-run